[phases.setup]
nixPkgs = ["python311", "gcc", "pkg-config"]

[phases.install]
cmds = ["pip install uv", "uv sync"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "uv run python main.py"
