services:
  - type: web
    name: data-analyst-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py main:app
    envVars:
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false  # This will need to be set manually in Render dashboard
    healthCheckPath: /health
